/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eje6lab1c1;

import eje6lab1c1.modelo.Producto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author norma
 */
public class buscarNombre extends javax.swing.JInternalFrame {
   
    private DefaultTableModel modelo =new DefaultTableModel() {
         public boolean isCellEditable(int f, int c){
            return false; 
         }

    };
    /**
     * Creates new form buscarNombre
     */
    public buscarNombre() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jTFProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();

        setClosable(true);

        jLNombre.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLNombre.setText("       Listado por Nombre");

        jLnombre.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLnombre.setText("Ingrese nombre Producto");

        jTFProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFProductoKeyReleased(evt);
            }
        });

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLnombre)
                                .addGap(18, 18, 18)
                                .addComponent(jTFProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombre)
                    .addComponent(jTFProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProductoKeyReleased
        // TODO add your handling code here:
         borrarFila();
        for(Producto prod :MenuGeneral.listaProductos){
            if (prod.getDescripcion().toLowerCase().startsWith(jTFProducto.getText().toLowerCase())) {
                modelo.addRow(new Object []{
                    prod.getCodigo(),
                    prod.getDescripcion(),
                    prod.getPrecio(),
                    prod.getStock()
                });
            }
        }
            
    }//GEN-LAST:event_jTFProductoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFProducto;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables
 private void armarCabecera(){
     modelo.addColumn("Código");
     modelo.addColumn("Descripción"); 
     modelo.addColumn("Precio");
     modelo.addColumn("Stock");
     jTProductos.setModel(modelo);
 }
private void borrarFila(){
    int f = modelo.getRowCount()-1;
    for(;f>=0;f--){
        modelo.removeRow(f);
    }
}

}
